# Generated by Django 4.2.2 on 2023-07-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='default_image.html', max_length=20000),
        ),
    ]
