# Generated by Django 4.2.2 on 2023-07-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readinglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('books', models.ManyToManyField(to='main_app.book')),
            ],
        ),
    ]
