# Generated by Django 4.2.2 on 2023-07-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_readinglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinglist',
            old_name='name',
            new_name='title',
        ),
    ]
